project_id = "jxklppwhgmndlivvtxdd"

[functions.meta-conversions-api]
verify_jwt = false

[functions.send-new-order-notification]
verify_jwt = false

[functions.send-delivery-notification]
verify_jwt = false

[functions.send-self-pickup-notification]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-seller-application-notification]
verify_jwt = false

[functions.send-review-request]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-email-change-code]
verify_jwt = false

[functions.verify-email-change-code]
verify_jwt = false